# Generated by Django 2.0.2 on 2018-12-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dianzhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pinglun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_text', models.CharField(max_length=256)),
                ('pl_dianzhan', models.IntegerField()),
                ('pl_riqi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tiezi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tz_img', models.CharField(max_length=256)),
                ('tz_title', models.CharField(max_length=64)),
                ('tz_text', models.CharField(max_length=500)),
                ('tz_liulan', models.IntegerField(default='0')),
                ('tz_huifu', models.IntegerField(default='0')),
                ('tz_riqi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=32)),
                ('u_password', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=8)),
                ('age', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('quanxian', models.IntegerField(default='1')),
            ],
        ),
        migrations.AddField(
            model_name='tiezi',
            name='tzu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backmanage.User'),
        ),
        migrations.AddField(
            model_name='pinglun',
            name='pl_tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backmanage.Tiezi'),
        ),
        migrations.AddField(
            model_name='pinglun',
            name='pl_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backmanage.User'),
        ),
        migrations.AddField(
            model_name='dianzhan',
            name='dz_plid',
            field=models.ForeignKey(on_delete=False, to='backmanage.Pinglun'),
        ),
        migrations.AddField(
            model_name='dianzhan',
            name='dz_tid',
            field=models.ForeignKey(on_delete=False, to='backmanage.Tiezi'),
        ),
        migrations.AddField(
            model_name='dianzhan',
            name='dz_uid',
            field=models.ForeignKey(on_delete=False, to='backmanage.User'),
        ),
    ]
