# Generated by Django 2.0.2 on 2018-12-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backmanage', '0004_auto_20181206_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.BigIntegerField(),
        ),
    ]
