# Generated by Django 2.0.2 on 2018-12-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backmanage', '0006_auto_20181207_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_img',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
