# Generated by Django 2.0.2 on 2019-01-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backmanage', '0008_auto_20190114_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
