# Generated by Django 2.0.2 on 2019-01-17 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backmanage', '0009_auto_20190116_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoucang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='tiezi',
            name='tz_shoucang',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shoucang',
            name='sc_tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backmanage.Tiezi'),
        ),
        migrations.AddField(
            model_name='shoucang',
            name='sc_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backmanage.User'),
        ),
    ]
