# Generated by Django 2.0.2 on 2019-01-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backmanage', '0010_auto_20190117_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dianzhanhf',
            name='dz_tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backmanage.Pinglun'),
        ),
    ]
