# Generated by Django 2.0.2 on 2019-01-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backmanage', '0011_auto_20190122_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dianzhanhf',
            old_name='dz_tid',
            new_name='dz_plid',
        ),
    ]
