# Generated by Django 2.0.2 on 2019-01-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backmanage', '0012_auto_20190122_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='huifu',
            name='hf_huifuid',
            field=models.IntegerField(null=True),
        ),
    ]
