# Generated by Django 2.0.2 on 2019-01-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backmanage', '0013_huifu_hf_huifuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='huifu',
            name='hf_huifu_uid',
            field=models.IntegerField(null=True),
        ),
    ]
