# Generated by Django 2.0.2 on 2019-01-23 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backmanage', '0015_auto_20190122_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xiaoxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xx_fauid', models.IntegerField()),
                ('xx_text', models.CharField(max_length=512)),
                ('xx_riqi', models.DateField()),
                ('xx_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backmanage.User')),
            ],
        ),
    ]
